version: '3'

services:

  atlas:
    image: wombach/docker-apache-atlas:2.2.0.4
    container_name: atlas
    command: "/tmp/atlas-config/startup.sh"
    volumes:
      - atlas-config:/tmp/atlas-config
      - atlas:/opt/apache-atlas-2.2.0/data
    network_mode: service:dev
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak-config/atlas-dev.json
      KEYCLOAK_PORT: 8180
    volumes:
      - keycloak-config:/tmp/keycloak-config
      - keycloak-data:/opt/jboss/keycloak/standalone/data
      - keycloak-settings:/opt/jboss/keycloak/standalone/configuration
    network_mode: service:dev
    restart: unless-stopped

volumes:
  atlas:
  atlas-config:
  keycloak-config:
  keycloak-data:
  keycloak-settings:
