version: '3'

services:

  dev:
    image: flink:1.17.0
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: localhost"
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
      ATLAS_SERVER_URL: "http://localhost:21000/api/atlas"
      ELASTICSEARCH_APP_SEARCH_INDEX_NAME: "app_search_documents"
      ELASTICSEARCH_STATE_INDEX_NAME: "publish_state"
      ELASTICSEARCH_USERNAME: "user"
      ELASTICSEARCH_PASSWORD: "password"
      ELASTICSEARCH_ENDPOINT: "http://localhost:9200"
      KAFKA_APP_SEARCH_TOPIC_NAME: "app_search_documents"
      KAFKA_PUBLISH_STATE_TOPIC_NAME: "publish_state"
      KAFKA_BOOTSTRAP_SERVER_HOSTNAME: "localhost"
      KAFKA_BOOTSTRAP_SERVER_PORT: "9092"
      KAFKA_CONSUMER_GROUP_ID: "13"
      KAFKA_PRODUCER_GROUP_ID: "13"
      KAFKA_ERROR_TOPIC_NAME: "DEAD_LETTER_BOX"
      KAFKA_SOURCE_TOPIC_NAME: "ATLAS_ENTITIES"
      KEYCLOAK_CLIENT_ID: "m4i_atlas"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_REALM_NAME: "atlas-dev"
      KEYCLOAK_SERVER_URL: "http://localhost:8180/auth/"
      KEYCLOAK_USERNAME: "admin"
    command: "taskmanager --cap-add=SYS_PTRACE --security-opt seccomp=unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ..:/workspace:cached
      - atlas-config:/tmp/atlas-config
      - keycloak-config:/tmp/keycloak-config
      - keycloak-settings:/tmp/keycloak-settings
      - checkpoints:/tmp/flink-checkpoints-directory

  pyflink-jobmanager:
    build:
      context: .
      dockerfile: ../docker/images/pyflink/Dockerfile
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: localhost"
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
    command: jobmanager
    volumes:
      - checkpoints:/tmp/flink-checkpoints-directory
    network_mode: service:dev
    restart: unless-stopped

volumes:
  atlas-config:
  keycloak-config:
  keycloak-settings:
  checkpoints:
