version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    volumes:
      - certs7:/usr/share/elasticsearch/config/certs
      - esdata7:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elasticpw
      - bootstrap.memory_lock=true
    network_mode: service:dev
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl -s http://localhost:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    volumes:
      - certs7:/usr/share/kibana/config/certs
      - kibanadata7:/usr/share/kibana/data
    environment:
      - ELASTIC_PASSWORD=elasticpw
      - KIBANA_PASSWORD=kibanapw
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://localhost:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibanapw
    network_mode: service:dev
    restart: unless-stopped
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  esdata7:
  kibanadata7:
  certs7:
