version: '3'

services:
  dev:
    image: mcr.microsoft.com/devcontainers/python:1-3.10-bullseye
    environment:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    command: /bin/sh -c "while sleep 1000; do :; done"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ELASTICSEARCH_USERNAME=user"
      - "ELASTICSEARCH_PASSWORD=password"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    network_mode: service:dev
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    network_mode: service:dev
    restart: unless-stopped

  kafka-broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-broker
    depends_on:
      - zookeeper
    volumes:
      - code:/code
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    network_mode: service:dev
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:29092
      - SERVER_PORT=8082
    network_mode: service:dev
    restart: unless-stopped

  pyflink-jobmanager:
    image: pyflink-kafka:0.1
    container_name: pyflink-jobmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: pyflink-jobmanager"
    command: jobmanager
    volumes:
      - checkpoints:/tmp/flink-checkpoints-directory
    network_mode: service:dev
    restart: unless-stopped

  pyflink-taskmanager:
    image: pyflink-kafka:0.1
    container_name: pyflink-taskmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: pyflink-jobmanager"
    command: taskmanager
    depends_on:
      - pyflink-jobmanager
    volumes:
      - checkpoints:/tmp/flink-checkpoints-directory
    network_mode: service:dev
    restart: unless-stopped

volumes:
  esdata:
  checkpoints:
  code:
