version: '3'

services:

  atlas:
    image: wombach/docker-apache-atlas:2.2.0.4
    container_name: atlas
    command: "/tmp/atlas-config/startup.sh"
    volumes:
      - /tmp/atlas-config:/tmp/atlas-config
      - atlas:/opt/apache-atlas-2.2.0/data
    network_mode: service:dev
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: aureliusatlas/docker-keycloak:16.1.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak-config/atlas-dev.json
      KEYCLOAK_PORT: 8180
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    network_mode: service:dev
    restart: unless-stopped
    command: ["-b 0.0.0.0", "-bmanagement 0.0.0.0", "-Djboss.http.port=$KEYCLOAK_PORT"]

volumes:
  atlas:
  atlas-config:
  keycloak-data:

configs:
  keycloak-config:
    file: ../keycloak/config/atlas-dev.json
    target: /tmp/keycloak-config/atlas-dev.json
  keycloak-settings:
    file: ../keycloak/settings/standalone.xml
    target: /opt/jboss/keycloak/standalone/configuration/standalone.xml
