version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ELASTICSEARCH_USERNAME=user"
      - "ELASTICSEARCH_PASSWORD=password"
      - ELASTICSEARCH_ENDPOINT=http://localhost:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    network_mode: service:dev
    restart: unless-stopped

volumes:
  esdata:
