version: '3'

services:

  dev:
    image: flink:1.17.0
    container_name: dev
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: localhost"
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
      ELASTICSEARCH_USERNAME: "user"
      ELASTICSEARCH_PASSWORD: "password"
      ELASTICSEARCH_INDEX: "atlas-dev-audit"
      ELASTICSEARCH_ENDPOINT: "http://localhost:9200"
      KAFKA_BOOTSTRAP_SERVER_HOSTNAME: "localhost"
      KAFKA_BOOTSTRAP_SERVER_PORT: "9092"
      KAFKA_CONSUMER_GROUP_ID: "13"
      KAFKA_PRODUCER_GROUP_ID: "13"
      KAFKA_ERROR_TOPIC_NAME: "DEAD_LETTER_BOX"
      KAFKA_SOURCE_TOPIC_NAME: "ENRICHED_ENTITIES"
    command: "taskmanager --cap-add=SYS_PTRACE --security-opt seccomp=unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ..:/workspace:cached
      - checkpoints:/tmp/flink-checkpoints-directory

  pyflink-jobmanager:
    build:
      context: .
      dockerfile: ../docker/images/pyflink/Dockerfile
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: localhost"
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
    command: jobmanager
    volumes:
      - checkpoints:/tmp/flink-checkpoints-directory
    network_mode: service:dev
    restart: unless-stopped

volumes:
  code:
