version: '3'

services:

  atlas:
    image: wombach/docker-apache-atlas:2.2.0.4
    container_name: atlas
    command: "/workspaces/flink-ci/docker/docker-compose-atlas/startup.sh"
    volumes:
      - atlas:/opt/apache-atlas-2.2.0/data
      - ..:/workspaces/flink-ci:cached
    network_mode: service:dev
    restart: unless-stopped

volumes:
  atlas:
