name: CI

# Trigger the workflow on both push (to the main repository, on the main branch)
# and pull requests (against the main repository, but from any repo, from any branch).
on:
  push:
    branches:
      - master
  pull_request:

# Brand new concurrency setting! This ensures that not more than one run can be triggered for the same commit.
# It is useful for pull requests coming from the main repository since both triggers will match.
concurrency: lint-${{ github.sha }}

jobs:
  ci:
    runs-on: ubuntu-latest

    container: flink:1.17.0

    env:
      POETRY_VERSION: "1.6.1"
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
      PYTHON_VERSION: "3.10"

    steps:
      - name: Install git
        run: |
          apt-get update
          apt-get install -y git

      - name: Checks out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}, Poetry and Dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Check if git is installed
        run: |
          echo $PWD
          [ -d ".git" ] && echo "Directory .git exists." || echo "Error: Directory .git does not exist."
          git --help

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
        continue-on-error: true

      - name: Print pre-commit log
        run: while read p; do echo "$p" done < /github/home/.cache/pre-commit/pre-commit.log

      - name: Unit testing
        run: |
          poetry run pytest
